### ISSUE TITLE
Typo mistake on "INSTEAD Клуб" page

### ISSUE THREAD

**Issue by ghost** [instead-hub/instead-hub.github.io#5]
- https://instead-hub.github.io/page/club/

> А также, вы можете воспользоваться caesium и чиать/писать сообщения прямо из вашего Unix.

Change `чиать` to `читать`.

> Интерфейс цезия напомнинает GoldEd (для тех, кто в крусе).

Change `в крусе` to `в курсе`.

P.S.: Also, maybe, change "из вашего Unix" to "на вашем Unix" or "из-под вашего Unix".

**Comment by hugeping** [comment]
fxd

**Comment by ghost** [comment]
> Интерфейс цезия напомнинает GoldEd (для тех, кто в крусе).

Change `в крусе` to `в курсе`.

**Comment by hugeping** [comment]
fxd

**Comment by ghost** [comment]
> - https://github.com/spline1986/caesium

Also, change link to "caesium"

- https://github.com/idec-net/caesium

Think, that is all now ;-)

**Comment by hugeping** [comment]
fxd :)
